baseurl = "https://maronghe.github.io/"
title = "LoganMa's Blog"
theme = "pulp"
canonifyurls = true
asCJKLanguage = true
# pygmentsCodefences = true
# pygmentsUseClasses = true
# googleAnalytics = "{your tracking code}"

[params]
    author = "马荣贺(Logan Ma)"
    avatar = "loganma.jpeg"
    favicon = "horseface.ico"
    description = """
		Welcome to my blog, I am a primary school student in Golang. For now, this blog is used to record my study recording only. So perhaps some of the artciles' main idea from other blog. If there is any infringement please contact me and I will delete it as soon as possible. Hope to leave your valuable comments. Thank you very much. 
    """
    publicationYear = "2020"
    # listPageDateFormat = "January, 2006" # See https://gohugo.io/functions/format/
    # singlePageDateFormat = "January 2, 2006"
    # custom_css = ["/css/custom.css"]
    # custom_js = ["/js/custom.js"]

# Make sure setting a following option for search bar to work
[outputs]
    section = ["JSON", "HTML"]
    taxonomy = ["JSON", "HTML"]

[[menu.main]]
    identifier = "blog"
    # name = "Blog" #If display text link, cancel comment out
    pre = "<i class='fa fa-book-open fa-lg'></i>" #Choose your favorite font from Font Awesome
    url = "/archives/"
    weight = 10

[[menu.main]]
    identifier = "readings"
    # name = "Twitter"
    pre = "<i class='fab fa-twitter fa-lg'></i>"
    url = "https://github.com/maronghe/Readings/blob/master/README.md"
    weight = 20

[[menu.main]]
    identifier = "github"
    # name = "GitHub"
    pre = "<i class='fab fa-github fa-lg'></i>"
    url = "https://github.com/maronghe"
    weight = 20

[[menu.main]]
    identifier = "email"
    # name = "Email"
    pre = "<i class='fa fa-envelope fa-lg'></i>"
    url = "mailto:loganma0209@gmail.com"
    weight = 30
